set_property SRC_FILE_INFO {cfile:{C:/Users/Acer/Downloads/HW-Syn-Lab-master1/HW-Syn-Lab-master/Lab06/Lab06.srcs/constrs_1/new/Basys 3 Master.xdc} rfile:{../../../../../Downloads/HW-Syn-Lab-master1/HW-Syn-Lab-master/Lab06/Lab06.srcs/constrs_1/new/Basys 3 Master.xdc} id:1} [current_design]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN W5 IOSTANDARD LVCMOS33} [get_ports clk]
set_property src_info {type:XDC file:1 line:110 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U18 [get_ports btnC]
set_property src_info {type:XDC file:1 line:266 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B18 [get_ports RsRx]
set_property src_info {type:XDC file:1 line:268 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A18 [get_ports RsTx]
